datasets:
  dataset_name: "waymo"
  train:
    waymo: 
      root: "/path/to/datasets/waymococo_f0/training_video_tensors"
      image_size: 512
      number_context_latents: 4
      number_target_latents: 12
      path_annotations: "/path/to/datasets/waymococo_f0/annotations/instances_train2020.json"
      resize: false
      horizontal_flip: true
      reverse_flip: false
  val_mini:
    waymo:
      root: "/path/to/datasets/waymococo_f0/validation_video_tensors"
      image_size: ${datasets.train.waymo.image_size}
      number_context_latents: ${datasets.train.waymo.number_context_latents}
      number_target_latents: ${datasets.train.waymo.number_target_latents}
      resize: ${datasets.train.waymo.resize}
      path_annotations: "/path/to/datasets/waymococo_f0/annotations/instances_val2020.json"
      horizontal_flip: false
      reverse_flip: false
  val:
    waymo:
      root: "/path/to/datasets/waymococo_f0/validation_video_tensors"
      image_size: ${datasets.train.waymo.image_size}
      number_context_latents: ${datasets.train.waymo.number_context_latents}
      number_target_latents: ${datasets.train.waymo.number_target_latents}
      resize: ${datasets.train.waymo.resize}
      path_annotations: "/path/to/datasets/waymococo_f0/annotations/instances_val2020.json"
      horizontal_flip: false
      reverse_flip: false

model:
  model_name: "dino_wm"
  image_size: ${datasets.train.waymo.image_size}
  patch_size: 16
  backbone:
    backbone_name: dinov3
    pretrained_model_name: "facebook/dinov3-vits16-pretrain-lvd1689m"
  dino_wm:
    number_context_latents: ${datasets.train.waymo.number_context_latents}
    input_dim: 384
    dim: 1024
    depth: 6
    heads: 8
    mlp_dim: 1024
    dim_head: 64
    dropout: 0.1
    emb_dropout: 0.0
    pool: "mean"

trainer:
  trainer_type: trainer_deterministic
  use_mixed_precision: false
  use_dinov3_layer_norm: True
  average_intermediate_layers: true
  extract_single_layer: null
  checkpoint_every: 10
  number_context_latents: ${datasets.train.waymo.number_context_latents}
  number_target_latents: ${datasets.train.waymo.number_target_latents}
  training:
    lr: 5e-4
    warmup_epochs: 4
    weight_decay: 0
    batch_size_per_gpu: 2
    epochs: 60
    log_freq: 5
    use_bptt: false
    ema_decay: null
    gradient_clipping: true
    gradient_clipping_max_norm: 0.6
    detector_loss:
      enabled: false
      weight: 1.0
      time_weighting: "none"
  evaluation:
    batch_size_per_gpu: 2
    eval_every: ${trainer.checkpoint_every}
    eval_first: true
    do_final_full_evaluation: false

loss:
  _target_: losses.DinoWMLoss
  loss_fn:
    _target_: torch.nn.L1Loss
  loss_name: loss_total
  monitor_loss_fn:
    _target_: torch.nn.L1Loss
    reduction: "none"
  monitor_loss_name: l1_latents
  weight_loss: 1.0

downstream_loss:
  _target_: losses.DownstreamLoss
  loss_fn:
    _target_: torch.nn.L1Loss

evaluator:
  _target_: evaluators.evaluator.FlowMatchingEvaluatorWaymoFastV2
  validate_mini_set: false

evaluation_detection:
  path_annotations_eval_mini: ${datasets.val_mini.waymo.path_annotations}
  path_annotations_eval: ${datasets.val.waymo.path_annotations}
  val_img_path: "/path/to/datasets/waymococo_f0/val2020"
  model_cfg_path: "/path/to/detrex/projects/dino/configs/models/dino_vitdet_dinov3_multi_layer_pooler_512_w_layer_norm.py"
  checkpoint_path: "/path/to/checkpoints/detectors/dinov3_multi_layer_pooler_w_layer_norm/model_final.pth"

seed: 42
compile: false
eval_only: false
eval_only_use_mini: false
