inherits:
- ../../base/384/dinov3_waymo_512_vits_16_384_flow_matching_rae_base.yaml

stage_2:
  params:
    depth: [8, 2]
    

trainer:
  use_mixed_precision: false
  training:
    lr: 8.91e-4
    batch_size_per_gpu: 1
  evaluation:
    batch_size_per_gpu: 1
