inherits:
  - ../../base/384/dinov3_waymo_512_vits_16_384_flow_matching_rae_base.yaml

eval_only: True
eval_only_use_mini: true

trainer:
  checkpoint_path: "/path/to/checkpoints/flow_wm/flow_matching_rae_dinov3_waymo_shift13/epoch_0180.pt"

evaluation_decoder:
  cfg_path: "./configs/dinov3/image_decoder_waymo/sweep/384/dinov3_waymo_512_vits16_image_decoder_l1_lr15e5_hd1024_rb8_lp01.yaml"
  checkpoint_path: "./experiments/dinov3/image_decoder_waymo/sweep/384/dinov3_waymo_512_vits16_image_decoder_l1_lr15e5_hd1024_rb8_lp01/checkpoints/epoch_0040.pt"
  save_decoded_videos: true
  fps: 10
